advance program 
universal function 
searching
sorting
filtering in numpy

# 🔢 NumPy Cheat Sheet

## 1. Universal Functions (ufuncs)
- `np.add(x, y)` → Element-wise addition
- `np.subtract(x, y)` → Element-wise subtraction
- `np.multiply(x, y)` → Element-wise multiplication
- `np.divide(x, y)` → Element-wise division
- `np.power(x, y)` → Raise elements of x to power y
- `np.sqrt(x)` → Square root
- `np.exp(x)` → Exponential
- `np.log(x)` → Natural log
- `np.sin(x), np.cos(x), np.tan(x)` → Trigonometric functions

## 2. Searching
- `np.where(arr > 5)` → Indices where condition is true
- `np.argmax(arr)` → Index of max element
- `np.argmin(arr)` → Index of min element
- `np.nonzero(arr)` → Indices of non-zero elements
- `np.in1d(arr1, arr2)` → Check if elements of arr1 are in arr2

## 3. Sorting
- `np.sort(arr)` → Sorted copy of array
- `arr.sort()` → Sort array in-place
- `np.argsort(arr)` → Indices that would sort array
- `np.unique(arr)` → Unique sorted values
- `np.partition(arr, k)` → Partitioned array (k-th element in correct position)

## 4. Filtering
- `arr[arr > 5]` → Filter elements greater than 5
- `arr[(arr % 2) == 0]` → Filter even numbers
- `np.isin(arr, [2,4,6])` → Boolean mask for membership
- `np.extract(condition, arr)` → Extract elements satisfying condition



# 🔢 Universal Functions (ufuncs) in NumPy

## Definition
A **Universal Function (ufunc)** in NumPy is a **vectorized function** that performs 
**fast element‑wise operations** on arrays.  
- Implemented in C for speed  
- Supports **broadcasting** across different shapes  
- Works on scalars, 1D, 2D, and higher‑dimensional arrays  

👉 In short: **ufuncs = optimized element‑wise math operations in NumPy.**

## Computations with NumPy
NumPy provides efficient functions for:
- **Arithmetic** → add, subtract, multiply, divide  
- **Statistical** → mean, median, std, var  
- **Aggregate** → sum, min, max, prod  
- **Trigonometric & Exponential** → sin, cos, exp, log, sqrt  


In [ ]:
import numpy as np 
a = np.array([1,2,3])
b = np.array([4,5,6])
c = np.array([8,9,10])
print (np.add(a,b))
print(np.add(b,c))


[5 7 9]
[12 14 16]


absolute

In [4]:
import numpy as np
x = np.array([-2,-1,0,1,2])
np.absolute(x)

array([2, 1, 0, 1, 2])

exponment and logarithm 

In [ ]:
x = [1,2,3]
np.exp(x)
np.exp2(x) #floating value

array([2., 4., 8.])

In [9]:
x = np.array ([1,2,3])
np.log(x)
np.log2(x)
np.log10(x)

array([0.        , 0.30103   , 0.47712125])

# ⚡ Advanced Universal Functions (ufuncs) in NumPy

## Definition
Universal Functions (ufuncs) are **vectorized functions** in NumPy that perform 
**fast element-wise operations** on arrays.  
Advanced features extend their power with options like memory efficiency, 
conditional execution, cumulative operations, and broadcasting.

---

## 1. Out Parameter
**Type:** Memory optimization  
**Definition:** Stores results directly in an existing array instead of creating a new one.  
**Example:**
```python
import numpy as np
a = np.array([1,2,3])
b = np.array([4,5,6])
out_arr = np.empty_like(a)

np.add(a, b, out=out_arr)
print(out_arr)   # [5 7 9]


In [11]:
import numpy as np
a = np.arange(2,20,2)
print(a)
z = np.empty(9)
print(z)
print(np.multiply(a,10,out =z))


[ 2  4  6  8 10 12 14 16 18]
[1.e-323 2.e-323 3.e-323 4.e-323 5.e-323 6.e-323 7.e-323 8.e-323 9.e-323]
[ 20.  40.  60.  80. 100. 120. 140. 160. 180.]


# ⚡ Aggregation Methods in NumPy Universal Functions (ufuncs)

## Definition
Aggregation methods in ufuncs allow you to **combine array elements** using 
cumulative operations like sum, product, etc.  
They provide **fast reductions** and **step-wise results**.

---

## 1. Reduce
**Type:** Cumulative aggregation  
**Definition:** Applies the ufunc cumulatively across an axis → returns a single aggregated result.  
**Example:**
```python
import numpy as np
arr = np.array([1, 2, 3, 4])

print(np.add.reduce(arr))       # 10
print(np.multiply.reduce(arr))  # 24

---

## 2. Aggregation Method: Accumulate

** Type**
Step-wise cumulative

## Definition
The **`accumulate`** method in NumPy ufuncs returns the **intermediate results** 
of a cumulative operation.  
- Unlike `reduce` (which gives only the final result),  
- `accumulate` shows the **step-by-step progression** of the operation.

## Example
```python
import numpy as np

arr = np.array([1, 2, 3, 4])

print(np.add.accumulate(arr))       # [1 3 6 10]
print(np.multiply.accumulate(arr))  # [1 2 6 24]


In [ ]:
x = np.arange(1,11)
print(x)
np.add.reduce(x)
np.add.accumulate(x)
'''
np.arange(1,11) → [1,2,3,4,5,6,7,8,9,10]

np.add.reduce(x) → adds all elements → 55

np.add.accumulate(x) → shows running sum:

Step1: 1

Step2: 1+2=3

Step3: 3+3=6

Step4: 6+4=10

… → final [1,3,6,10,15,21,28,36,45,55]'''


[ 1  2  3  4  5  6  7  8  9 10]


array([ 1,  3,  6, 10, 15, 21, 28, 36, 45, 55])

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4])

# Aggregate (final result)
print(np.sum(arr))    # 10
print(np.prod(arr))   # 24

# Step-wise cumulative
'''np.cumsum(arr) → cumulative sum of array elements (step‑wise).
np.add.accumulate(arr) → does the same, but written using the ufunc method.'''

print(np.cumsum(arr))   # [ 1  3  6 10]
print(np.cumprod(arr))  # [ 1  2  6 24]


10
24
[ 1  3  6 10]
[ 1  2  6 24]


In [ ]:
#create a matrix 10*10 