-> flattering = converting a nested data structure (like a list of lists or a dictionary of dictionaries) into a single, one‑dimensional structure. For example, turning [[1,2],[3,4]] into [1,2,3,4]. It’s commonly used in data processing, JSON handling, and machine learning preprocessing.

-> Definition: Flattening = removing hierarchy and nesting, producing a flat sequence or dictionary.
## Why Flattening Matters in Python

- **Easier operations**: Functions like `sum()`, filtering, or iteration work more smoothly on flat structures.  
- **Library compatibility**: Many libraries (NumPy, Pandas, ML frameworks) expect flat structures for efficient processing.  

---

## Common Use Cases

- **Cleaning JSON responses**  
- **Preparing tabular data for analysis**  
- **Simplifying nested dictionaries for storage or transmission**  


In [1]:
import numpy as np

n = np.arange(1, 11)   # creates array [1,2,3,4,5,6,7,8,9,10]
n[5] = 20              # replaces the element at index 5 (the 6th element) with 20
print(n)               # prints the updated array
print(id(n))           # prints the memory address (unique ID) of the array object


[ 1  2  3  4  5 20  7  8  9 10]
2021508359312


# 📌 Copy vs View vs Base in NumPy

## Base
- `.base` attribute tells you whether an array is a **view** of another array.  
- If `arr2.base is arr1`, then `arr2` is just a view backed by `arr1`.  
- If `.base` is `None`, the array owns its data (it’s independent, usually from a copy).  

---

## View
- A **view** is not a copy — it’s just another “window” into the same data.  
- Example: slicing in NumPy (`arr[1:3]`) produces a **view**.  
- Any modification in the view reflects in the original array because they share the same memory.  

---

## Copy
- **Shallow Copy** → Creates a new object but references the same elements inside.  
- **Deep Copy** → Creates a completely independent duplicate, including nested structures.  
- In NumPy, `copy()` is effectively a **deep copy** (changes in the new array don’t affect the original).  
- Example: `arr.copy()` makes a new array with the same values, independent of the original.  


In [2]:
import numpy as np

n = np.arange(1, 29)   # must have 28 elements to reshape into (4,7)
y = n.reshape((4, 7)).base

print(y)       # prints the original array that backs the view
print(id(y))   # prints the memory ID of that base array


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28]
2021881173296


In [3]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])  # original array
x = arr.view()   # creates a view (shares data with arr)
y = arr.copy()   # creates a copy (independent data)

arr[0] = 100     # modify the first element of arr

print(arr)       # modified original array
print(x)         # view reflects the change
print(y) 
id(arr)        # copy does NOT reflect the change


[100   2   3   4   5   6   7   8   9  10]
[100   2   3   4   5   6   7   8   9  10]
[ 1  2  3  4  5  6  7  8  9 10]


2125564032080

# NumPy: View, Copy, and Base

## #View
- A **view** is just another "window" into the same data.  
- Changes in the original array reflect in the view, and vice versa.  

```python
import numpy as np

arr = np.array([1,2,3,4,5])
x = arr.view()   # creates a view
arr[0] = 100     # modify original

print(arr)  # [100   2   3   4   5]
print(x)    # [100   2   3   4   5] → reflects change


# NumPy: #Copy

- A **copy** is an independent duplicate of the array.  
- Changes in the original do not affect the copy.  

```python
import numpy as np

arr = np.array([1,2,3,4,5])
y = arr.copy()   # creates a copy
arr[0] = 200     # modify original

print(arr)  # [200   2   3   4   5]
print(y)    # [  1   2   3   4   5] → unaffected


# NumPy: #Base

- `.base` attribute tells you whether an array is a **view** of another array.  
- If `.base` points to another array → it’s a **view**.  
- If `.base is None` → it owns its data (**copy**).  

```python
import numpy as np

arr = np.arange(1, 11)
view_arr = arr[2:7]     # slicing → view
copy_arr = arr.copy()   # copy

print(view_arr.base is arr)  # True → view shares data
print(copy_arr.base)         # None → copy owns data


In [4]:
import numpy as np

arr = np.array([1,2,3,4,5,6,7,8,9,10])  # original array
x = arr.view()   # creates a view (shares data with arr)
y = arr.copy()   # creates a copy (independent data)

arr[0] = 100     # modify the first element of arr

print(arr)       # modified original array
print(x)         # view reflects the change
print(y) 
id(arr)        # copy does NOT reflect the change
print(id(x))      # prints the memory ID of the view
print(id(y))      # prints the memory ID of the copy
print(y.base)   # prints None, since y is a copy and does not share data with arr


[100   2   3   4   5   6   7   8   9  10]
[100   2   3   4   5   6   7   8   9  10]
[ 1  2  3  4  5  6  7  8  9 10]
2125564713776
2125564032272
None


copy jab hum use krenge toh voh khud ka adress own krega pr jab hum view use krenge toh voh original array ka address share karega. isliye jab hum view me changes karenge toh original array me bhi changes reflect honge, lekin copy me changes nahi honge.
but how we checlk this 
we check this using base attribute. If we check the base attribute of a view, it will point to the original array, while for a copy, it will be None. This is how we can confirm whether an array is a view or a copy.

In [ ]:
import numpy as np

x = np.random.randint(10, size=(2,3))
print("Original 2D array:\n", x)

# Flatten into 1D
x = x.reshape(-1)   # reshape is a method of the array, not standalone
print("Flattened array:\n", x)


In [ ]:
import numpy as np

# Create a 3x3 array
x = np.arange(1, 10).reshape(3, 3)
print("Original Array:\n", x)

# Transpose the array
print("Transposed Array:\n", x.T)

📌 Does transpose store data in a new location?
In NumPy, x.T (or x.transpose()) usually does not create a new copy of the data.

Instead, it creates a view of the same array with axes swapped.

That means the transposed array shares the same memory buffer as the original — no new storage is allocated.

🔎 Example
python
import numpy as np

x = np.arange(1,10).reshape(3,3)
print("Original:\n", x)

t = x.T
print("Transposed:\n", t)

print(t.base is x)  # True → it's a view, not a copy
✅ Output
Code
Original:
 [[1 2 3]
  [4 5 6]
  [7 8 9]]

Transposed:
 [[1 4 7]
  [2 5 8]
  [3 6 9]]

True
📖 Definition of Transpose
Transpose of an array means flipping it over its diagonal.

Rows become columns, and columns become rows.

In NumPy, .T or .transpose() is used to achieve this.

👉 So:

Transpose = view (same memory, different shape).

If you explicitly call .copy() on the transpose, then it will store data in a new location.

# 🔄 Rotation of Arrays in NumPy

## 📌 Using `np.rot90(m, k=1, axes(0,1))`
- Rotates an array by **90 degrees** counterclockwise.
- You can specify the number of rotations with the `k` parameter.
- Each rotation is 90°.
- axes the array is roated in the plane define by the axes 

```python
import numpy as np

x = np.arange(1,10).reshape(3,3)
print("Original:\n", x)

# Rotate 90° counterclockwise
rot1 = np.rot90(x)
print("90° Rotation:\n", rot1)

# Rotate 180°
rot2 = np.rot90(x, k=2)
print("180° Rotation:\n", rot2)

# Rotate 270°
rot3 = np.rot90(x, k=3)
print("270° Rotation:\n", rot3)


In [8]:
import numpy as np

# Create a 3x3 array
m = np.arange(1,10).reshape(3,3)
print("Original Array:\n", m)

# Rotate 90° counterclockwise (default axes = (0,1))
rot90 = np.rot90(m, k=1, axes=(0,1))
print("90° Rotation:\n", rot90)

# Rotate 180°
rot180 = np.rot90(m, k=2, axes=(0,1))
print("180° Rotation:\n", rot180)

# Rotate 270°
rot270 = np.rot90(m, k=3, axes=(0,1))
print("270° Rotation:\n", rot270)

Original Array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
90° Rotation:
 [[3 6 9]
 [2 5 8]
 [1 4 7]]
180° Rotation:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]
270° Rotation:
 [[7 4 1]
 [8 5 2]
 [9 6 3]]


# 🔗 Joining Arrays in NumPy

## 📌 Method 1: Using `concatenate()`
- Joins arrays along an existing axis.  
- You must specify the axis (default = 0).  

```python
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

joined = np.concatenate((a,b))
print(joined)   # [1 2 3 4 5 6]


📌 Method 2: Using stack()
it will be done vertical 
Joins arrays along a new axis.

Creates higher-dimensional arrays.

python
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

stacked = np.stack((a,b), axis=0)
print(stacked)
# [[1 2 3]
#  [4 5 6]]

📌 Method 3: Using hstack() and vstack()
hstack() → joins arrays horizontally (column-wise).

vstack() → joins arrays vertically (row-wise).

python
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

h = np.hstack((a,b))
print(h)   # [1 2 3 4 5 6]

v = np.vstack((a,b))
print(v)
# [[1 2 3]
#  [4 5 6]]

#📖 Summary
concatenate() → join along existing axis.

stack() → join along new axis (adds dimension).

hstack() / vstack() → join horizontally or vertically.